add user enablePreviewFeedback setting
vercel/schemas pull request #72
Opened 2022-07-28 21:44 UTC by natew

Adding a setting for User.enablePreviewFeedback, For use with new API endpoint and Preview Comments feature:

https://github.com/vercel/api/pull/13453/files

2022-08-01 23:24 UTC, gdborton approved these changes

2022-08-02 11:12 UTC, cramforce requested changes

2022-08-02 11:12 UTC, cramforce commented on user/index.js
> +	type: 'string',
Could this be an enum?

2022-08-02 20:53 UTC, natew commented on user/index.js
> +	type: 'string',
Ah, missed the enum use, fixed.

2022-08-02 20:53 UTC, merged